package game;

public enum Names {
    MeasureMan,
    TroubleyShoot,
    Assassin,
    NastyWar,
    DedicatedLucy,
    SweetyMonster,
    Creeper,
    SheepFucker,
    Skankhunt_26,
    LucyInTheSky,
    Volodya_Morda,
    SemenProtector,
    Caligula,
    PissuarOfHell,
    ChickenMacNuggets,
    TupleWarrior,
    MagicSpearman,
    MyLittlePony27,
    Necromancer,
    ShatterStar,
    Masters_Only,
    Lftfeet,
    Smooker,
    HerraserJohn,
    JokerChpoker,
    NudeBoy,
    mrBeast,
    BillyHurrington,
    VanDarkHolme,
    OnePieceMan,
}
